### ISSUE TITLE
Labels not showing

### ISSUE THREAD

**Issue by saiyamjain0012** [walterra/kibana-milestones-vis#8] opened 2019-06-27 09:26 UTC
The number of labels that are visible is maximum 3 in bottom style and 2 in above style.

**Comment by walterra** [comment] 2019-06-27 09:57
Hey, thanks for reporting this! Can you please post with which Elastic Stack version this is happening for you?

**Comment by saiyamjain0012** [comment] 2019-06-27 10:00
Hi thanks for the reply
Actually i researched a bit more and found the cause, the metrics are
selected based on number of counts and so only unique metrics are listed.
I was using your plugin as a flow chart of user activity via user logs so
could not display if redundant entries were observed.

Can you suggest some way to make a flow chart in KIBANA. I need to submit
the work as soon as possible, so it will be of great help if you could help.

Thanks

**Comment by walterra** [comment] 2019-06-27 23:11
Thanks for the update! I'm not aware of a dedicated flow chart plugin for Kibana but you could have a go at using the Vega plugin in combination with a Sankey visualization. Here's a blog post about it https://www.elastic.co/blog/sankey-visualization-with-vega-in-kibana

I'm going to close this issue since your original problem with the milestones plugin seems to be not a bug but related to your data structures. Feel free to reopen if you think the original issue is still worth more investigation.

**Closed as completed by walterra** 2019-06-27 23:11 UTC

**Comment by saiyamjain0012** [comment] 2019-06-28 05:24
Okay thanks sir, yeah I had a look at that sankey chart but I guess using
yours would be better.

Yeah close this issue as it's solved.
Thanks
